# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-17 19:21
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message="Can't be negative")])),
                ('category', models.CharField(choices=[('FD', 'Food'), ('CL', 'Clothes'), ('EN', 'Entertainment'), ('BL', 'Bills'), ('OT', 'Other')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Calculator')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01000000000000000020816681711721685132943093776702880859375'), message="Can't be negative")])),
                ('category', models.CharField(choices=[('SL', 'Salary'), ('DP', 'Deposit'), ('OT', 'Other')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('calculator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Calculator')),
            ],
        ),
    ]
